name: Sync "FrogPilot-Staging" to "MAKE-PRS-HERE"

on:
  push:
    branches:
      - FrogPilot-Staging
  workflow_dispatch:

env:
  SOURCE_BRANCH: FrogPilot-Staging
  DESTINATION_BRANCH: MAKE-PRS-HERE
  TZ: America/Phoenix

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Checkout destination branch
        run: |
          git fetch origin
          git checkout ${{ env.DESTINATION_BRANCH }}

      - name: Merge changes from source branch with conflicts resolved in favor of source
        run: |
          git merge --allow-unrelated-histories -X theirs origin/${{ env.SOURCE_BRANCH }}

      - name: Generate commit message with correct date suffix
        run: |
          DAY=$(TZ=${{ env.TZ }} date +"%-d")
          case $DAY in
            1|21|31) SUFFIX="st" ;;
            2|22) SUFFIX="nd" ;;
            3|23) SUFFIX="rd" ;;
            *) SUFFIX="th" ;;
          esac
          CURRENT_DATE=$(TZ=${{ env.TZ }} date +"%B ${DAY}${SUFFIX}, %Y Update")
          git commit --allow-empty -m "$CURRENT_DATE"
          git push origin ${{ env.DESTINATION_BRANCH }}
