name: Cherry-pick and Squash Commit

on:
  push:
    branches:
      - FrogPilot-Staging

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE_PREFIX: "$(TZ='America/Phoenix' date +'%B %dth, %Y') Update"
      SOURCE_BRANCH: "FrogPilot-Staging"
      TARGET_BRANCH: "MAKE-PRS-HERE"
      TEMP_BRANCH: "temp-branch"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - run: |
          git checkout -b ${{ env.TEMP_BRANCH }} origin/${{ env.SOURCE_BRANCH }}
          git reset --hard HEAD~1  # Ignore the last commit

      - run: git checkout ${{ env.TARGET_BRANCH }}

      - run: |
          git cherry-pick ${{ env.TEMP_BRANCH }} || echo "conflict" > conflict.txt

      - id: check_conflict
        run: |
          if [ -f conflict.txt ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - if: env.exists == 'true'
        run: |
          git checkout --theirs .
          git add .
          git cherry-pick --continue || echo "unresolved" > unresolved.txt

      - id: check_unresolved
        run: |
          if [ -f unresolved.txt ]; then
            echo "unresolved=true" >> $GITHUB_ENV
          else
            echo "unresolved=false" >> $GITHUB_ENV
          fi

      - if: env.unresolved == 'true'
        run: echo "Cherry-pick resulted in conflicts that could not be resolved automatically."

      - if: success() && env.exists == 'false'
        run: git push origin ${{ env.TARGET_BRANCH }}
