name: Update MAKE-PRS-HERE

on:
  push:
    branches:
      - FrogPilot-Staging

env:
  SOURCE_BRANCH: FrogPilot-Staging
  TARGET_BRANCH: MAKE-PRS-HERE

jobs:
  update-target-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0

      - name: Set Git user name and email
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Replace content with SOURCE_BRANCH minus last commit
        run: |
          git rm -rf .
          git fetch origin ${{ env.SOURCE_BRANCH }}
          COMMIT_HASH=$(git rev-parse origin/${{ env.SOURCE_BRANCH }}~1)
          git archive $COMMIT_HASH | tar -x
          git add .
          day=$(TZ='America/Phoenix' date '+%-d')
          suffix="th"
          case $day in
            1|21|31) suffix="st" ;;
            2|22) suffix="nd" ;;
            3|23) suffix="rd" ;;
          esac
          commit_message="$(TZ='America/Phoenix' date '+%B ')$day$suffix, $(TZ='America/Phoenix' date '+%Y') Update"
          git commit -m "$commit_message"
          git push origin ${{ env.TARGET_BRANCH }}
