name: Squash Commits and Cherry-Pick to MAKE-PRS-HERE

on:
  push:
    branches:
      - FrogPilot-Staging

jobs:
  squash-and-cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: FrogPilot-Staging

      - name: Set Git user name and email
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Get the second to last commit hash
        id: get-commit
        run: |
          commit_hash=$(git rev-parse HEAD~1)
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      - name: Create temporary branch starting from the second to last commit
        run: |
          git checkout -b temp-branch ${{ env.commit_hash }}

      - name: Squash all commits into one with today's date in Phoenix time zone
        run: |
          day=$(TZ='America/Phoenix' date '+%-d')
          suffix="th"
          if [ "$((day % 10))" -eq 1 ] && [ "$day" -ne 11 ]; then suffix="st"; fi
          if [ "$((day % 10))" -eq 2 ] && [ "$day" -ne 12 ]; then suffix="nd"; fi
          if [ "$((day % 10))" -eq 3 ] && [ "$day" -ne 13 ]; then suffix="rd"; fi
          commit_message="$(TZ='America/Phoenix' date '+%B ')$day$suffix, $(TZ='America/Phoenix' date '+%Y') Update"
          git reset --soft $(git rev-list --max-parents=0 HEAD)
          git commit -m "$commit_message"

      - name: Checkout MAKE-PRS-HERE branch
        run: |
          git fetch origin
          git checkout MAKE-PRS-HERE

      - name: Cherry-pick the squashed commit to MAKE-PRS-HERE branch
        run: |
          git cherry-pick $(git rev-parse temp-branch) -X theirs
          git push origin MAKE-PRS-HERE
