name: Cherry-pick and Squash Commit

on:
  push:
    branches:
      - FrogPilot-Staging

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Get the 2nd to newest commit hash on FrogPilot-Staging
        id: second_commit
        run: |
          git checkout FrogPilot-Staging
          second_commit=$(git rev-parse HEAD~1)
          echo "SECOND_COMMIT=$second_commit" >> $GITHUB_ENV

      - name: Create and checkout new branch from 2nd to newest commit
        run: |
          git checkout -b new-branch-based-on-2nd-commit ${{ env.SECOND_COMMIT }}

      - name: Squash commits into one
        run: |
          TZ="America/Phoenix" date_today=$(date +"%B %dth, %Y Update")
          git reset --soft ${{ env.SECOND_COMMIT }}^
          git commit --amend -m "$date_today"

      - name: Checkout MAKE-PRS-HERE branch
        run: |
          git checkout MAKE-PRS-HERE

      - name: Cherry-pick the squashed commit
        run: |
          git cherry-pick new-branch-based-on-2nd-commit

      - name: Resolve any conflicts by using code from FrogPilot-Staging
        run: |
          git checkout --theirs .
          git cherry-pick --continue

      - name: Push changes to MAKE-PRS-HERE
        run: |
          git push origin MAKE-PRS-HERE
