name: Cherry-pick and Squash Commit

on:
  push:
    branches:
      - FrogPilot-Staging

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE_PREFIX: "$(TZ='America/Phoenix' date +'%B %dth, %Y') Update"
      SOURCE_BRANCH: "FrogPilot-Staging"
      TARGET_BRANCH: "MAKE-PRS-HERE"
      TEMP_BRANCH: "temp-branch"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - run: |
          git fetch origin ${{ env.SOURCE_BRANCH }}
          git checkout -b ${{ env.TEMP_BRANCH }} $(git rev-parse origin/${{ env.SOURCE_BRANCH }}~1)
          git reset --soft HEAD^
          git commit --amend -m "${{ env.COMMIT_MESSAGE_PREFIX }}"

      - run: git checkout ${{ env.TARGET_BRANCH }}

      - run: |
          git cherry-pick ${{ env.TEMP_BRANCH }} || echo "conflict" > conflict.txt

      - if: failure()
        run: |
          git checkout --theirs .
          git add .
          git cherry-pick --continue

      - if: success()
        run: git push origin ${{ env.TARGET_BRANCH }}

      - if: failure() && exists(conflict.txt)
        run: echo "Cherry-pick resulted in conflicts and could not be resolved automatically."
