name: Update Branch

env:
  SOURCE_BRANCH: FrogPilot-Staging
  IGNORE_COMMITS: 1
  TZ: America/Phoenix

on:
  push:
    branches:
      - FrogPilot-Staging

  workflow_dispatch:
    inputs:
      DESTINATION_BRANCH:
        description: 'Destination branch to update'
        required: true
        default: MAKE-PRS-HERE
      IGNORE_COMMITS:
        description: 'Number of commits to ignore'
        required: false
        default: 0

jobs:
  update-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          echo "DESTINATION_BRANCH=${{ github.event.inputs.DESTINATION_BRANCH }}" >> $GITHUB_ENV
          echo "IGNORE_COMMITS=${{ github.event.inputs.IGNORE_COMMITS }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to ${{ env.SOURCE_BRANCH }} branch
        run: git checkout ${{ env.SOURCE_BRANCH }}

      - name: Revert last ${{ env.IGNORE_COMMITS }} commits on ${{ env.SOURCE_BRANCH }} branch
        run: git reset --hard HEAD~${{ env.IGNORE_COMMITS }}

      - name: Merge ${{ env.SOURCE_BRANCH }} branch into ${{ env.DESTINATION_BRANCH }} branch
        run: |
          git checkout ${{ env.DESTINATION_BRANCH }}
          git merge --strategy=ours --allow-unrelated-histories ${{ env.SOURCE_BRANCH }} --no-commit

      - name: Commit the changes
        run: |
          date=$(TZ=$TZ date +"%B %dth, %Y")
          git commit -m "$date Update"

      - name: Push changes to ${{ env.DESTINATION_BRANCH }} branch
        run: git push origin ${{ env.DESTINATION_BRANCH }} --force
