name: Update MAKE-PRS-HERE Branch

on:
  push:
    branches:
      - FrogPilot-Staging
  workflow_dispatch:

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to FrogPilot-Staging branch
        run: git checkout FrogPilot-Staging

      - name: Revert last commit on FrogPilot-Staging branch
        run: git reset --hard HEAD~1

      - name: Merge FrogPilot-Staging branch into MAKE-PRS-HERE branch
        run: |
          git checkout MAKE-PRS-HERE
          git merge --strategy=ours FrogPilot-Staging --no-commit

      - name: Commit the changes
        run: |
          TZ="America/Phoenix"
          date=$(date +"%B %dth, %Y")
          git commit -m "$date Update"

      - name: Push changes to MAKE-PRS-HERE branch
        run: git push origin MAKE-PRS-HERE --force
