name: Sync "FrogPilot-Staging" to "MAKE-PRS-HERE"

on:
  push:
    branches:
      - FrogPilot-Staging
  workflow_dispatch:

env:
  SOURCE_BRANCH: FrogPilot-Staging
  DESTINATION_BRANCH: MAKE-PRS-HERE
  TZ: America/Phoenix

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch and checkout destination branch
        run: |
          git fetch origin ${{ env.DESTINATION_BRANCH }}:${{ env.DESTINATION_BRANCH }}
          git checkout ${{ env.DESTINATION_BRANCH }}

      - name: Merge changes from source branch
        run: |
          git merge -X theirs origin/${{ env.SOURCE_BRANCH }} --allow-unrelated-histories

      - name: Generate commit message with date suffix and push
        run: |
          DAY=$(TZ=${{ env.TZ }} date +"%-d")
          SUFFIX=$(case $DAY in 1|21|31) echo "st" ;; 2|22) echo "nd" ;; 3|23) echo "rd" ;; *) echo "th" ;; esac)
          CURRENT_DATE=$(TZ=${{ env.TZ }} date +"%B ${DAY}${SUFFIX}, %Y Update")
          git commit --allow-empty -m "$CURRENT_DATE"
          git push origin ${{ env.DESTINATION_BRANCH }}
