name: Sync "FrogPilot-Staging" to "MAKE-PRS-HERE"

on:
  push:
    branches:
      - FrogPilot-Staging
  workflow_dispatch:

env:
  SOURCE_BRANCH: FrogPilot-Staging
  DESTINATION_BRANCH: MAKE-PRS-HERE
  TZ: America/Phoenix

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch and checkout source branch
        run: |
          git fetch origin
          git checkout ${{ env.SOURCE_BRANCH }}

      - name: Create a temporary branch excluding the last commit
        run: |
          git checkout -b temp-branch
          git reset --hard HEAD~1

      - name: Checkout destination branch and merge changes
        run: |
          git checkout ${{ env.DESTINATION_BRANCH }}
          git merge --strategy-option ours temp-branch --no-commit

      - name: Squash and commit changes with date suffix
        run: |
          DAY=$(TZ=${{ env.TZ }} date +"%-d")
          case $DAY in
            1|21|31) SUFFIX="st" ;;
            2|22) SUFFIX="nd" ;;
            3|23) SUFFIX="rd" ;;
            *) SUFFIX="th" ;;
          esac
          CURRENT_DATE=$(TZ=${{ env.TZ }} date +"%B ${DAY}${SUFFIX}, %Y Update")
          git commit -m "$CURRENT_DATE"

      - name: Force push changes to destination branch
        run: |
          git push --force-with-lease origin ${{ env.DESTINATION_BRANCH }}

      - name: Clean up temporary branch
        run: |
          git branch -D temp-branch
